// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/ActionBar.vue')['default']
    DarkSwitcher: typeof import('./src/components/DarkSwitcher.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    TimeSchedular: typeof import('./src/components/TimeSchedular.vue')['default']
    TimezoneSearch: typeof import('./src/components/TimezoneSearch.vue')['default']
  }
}

export {}
